### ISSUE TITLE
Need a PR and issue template.

### ISSUE THREAD

**Issue by MadhavJivrajani** [QForestCommunity/launchpad#2]
Need a PR template for people to follow when the number of contributions grows.

**Comment by MadhavJivrajani** [comment]
Need an issue template as well. 
Thanks, @ShriprajwalK for pointing that out

**Comment by ShriprajwalK** [comment]
For the issue template: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
